title: <p align="center"> Emmy Phung </p>

logo: "/images/ava.png?raw=true"

description:
  <p align="center">
  <a href="https://github.com/Emmyphung/Resume/blob/master/Emmy%20Phung_Resume%2005.12.19.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/emmy-phung/">LinkedIn</a> |
  <a href="https://github.com/Emmyphung">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Data Science at New York University, Center for Data Science.
  My goal is to attain mastery over data science to translate consumer insights into data-intensive business solutions.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

