title: <p align="center">   </p>

logo: "/images/ava.png?raw=true"

description:
  <h1 align="center"> Emmy Phung </h1>
  <p align="center">
  <a href="https://emmyphung.github.io/Resume/">Resume</a> |
  <a href="https://www.linkedin.com/in/emmy-phung/">LinkedIn</a> |
  <a href="https://github.com/Emmyphung">GitHub</a>
  </p>
  
  
  <p align="justify">
  Hi, I am a Machine Learning Engineer soon graduating from my MS in Data Science at NYU (May 2021). I have research and industry experience in machine learning, deep learning for Natural Language Processing (NLP), probabilistic time series (specifically in finance domain) and recommender system.
 
  I aspire to turning ideas into actionable solutions and unlocking new potentials from data with my solid programming skills and theoretical knowledge.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

