title: <p align="center"> Emmy Phung </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://emmyphung.github.io/pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/emmy-phung/">LinkedIn</a> |
  <a href="https://github.com/Emmyphung">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Data Science at New York University, Center for Data Science.
  <br><br>
  [...]
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

