title: <p align="center">   </p>

logo: "/images/ava.png?raw=true"

description:
  <h1 align="center"> Emmy Phung </h1>
  <p align="center">
  <a href="https://emmyphung.github.io/Resume/">Resume</a> |
  <a href="https://www.linkedin.com/in/emmy-phung/">LinkedIn</a> |
  <a href="https://github.com/Emmyphung">GitHub</a>
  </p>
  
  
  <p align="justify">
  Hi, I am a Machine Learning Engineer soon to be graduating from my MS in Data Science at NYU (May 2021).
  <br>
  <br>
  I aspire to turn ideas into actionable solutions and unlock new potentials from data with my solid programming skills and theoretical knowledge in data science.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
timezone: America/New_York
future: true
